version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: DockerfileServer.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
      - "8080:8080"
    environment:
      - NODE_ENV=development
  frontend:
    build:
      context: ./client
      dockerfile: DockerfileClient.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development